# Generated by Django 2.0.7 on 2018-09-04 12:44

from django.db import migrations, models
import django.db.models.deletion
import editingservices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(choices=[('', 'Select One'), ('Partner', 'Partner'), ('Researcher', 'Researcher')], max_length=20)),
                ('article_title', models.CharField(max_length=250)),
                ('subject_name', models.CharField(blank=True, max_length=150, null=True)),
                ('word_count', models.CharField(blank=True, max_length=150, null=True)),
                ('paper_received', models.CharField(blank=True, max_length=10, null=True)),
                ('expected_delivery_date', models.CharField(blank=True, max_length=10, null=True)),
                ('paper_sent_author', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_received_on', models.CharField(blank=True, max_length=10, null=True)),
                ('booking_id', models.CharField(default=editingservices.models.create_id, editable=False, max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('pdf_authors_edit', models.CharField(blank=True, max_length=1000, null=True)),
                ('pdf_issue_date_edit', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_currency', models.CharField(choices=[('GBP', 'GBP(£)'), ('AUD', 'AUD(A$)'), ('Euro', 'Euro(€)'), ('USD', 'USD($)')], max_length=20)),
                ('english_editing', models.CharField(blank=True, choices=[('', '----'), ('English editing', 'English editing')], max_length=20, null=True)),
                ('english_editing_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('scientific_editing', models.CharField(blank=True, choices=[('', '----'), ('Scientific editing', 'Scientific editing')], max_length=20, null=True)),
                ('scientific_editing_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('presubmission_review', models.CharField(blank=True, choices=[('', '----'), ('Presubmission review', 'Presubmission review')], max_length=20, null=True)),
                ('presubmission_review_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('journal_selection', models.CharField(blank=True, choices=[('', '----'), ('Journal selection', 'Journal selection')], max_length=20, null=True)),
                ('journal_selection_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('paper_sent_editor', models.CharField(blank=True, max_length=10, null=True)),
                ('expected_returned_paper', models.CharField(blank=True, max_length=10, null=True)),
                ('editor_returned_paper', models.CharField(blank=True, max_length=10, null=True)),
                ('editor_invoice_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('editor_payment_sent', models.CharField(blank=True, max_length=10, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editingservices.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_serial_send_no', models.CharField(blank=True, max_length=250, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editingservices.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('', 'Select One'), ('Author', 'Author'), ('Co-author', 'Co-author')], max_length=20)),
                ('author_name', models.CharField(blank=True, max_length=150, null=True)),
                ('affiliation', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('author_country', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('tel', models.CharField(max_length=150)),
                ('orcid_id', models.CharField(max_length=350)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editingservices.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('education', models.CharField(max_length=150)),
                ('subject_covers', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(max_length=250)),
                ('editor_country', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('tel', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=50)),
                ('editor_note', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=150)),
                ('partner_contact', models.CharField(max_length=150)),
                ('partner_address', models.CharField(max_length=250)),
                ('partner_partner_country', models.CharField(max_length=50)),
                ('partner_email', models.CharField(max_length=150)),
                ('partner_tel', models.CharField(max_length=150)),
                ('partner_note', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_currency', models.CharField(choices=[('GBP', 'GBP(£)'), ('AUD', 'AUD(A$)'), ('Euro', 'Euro(€)'), ('USD', 'USD($)')], max_length=20)),
                ('english_editing', models.CharField(blank=True, choices=[('', '----'), ('English editing', 'English editing')], max_length=20, null=True)),
                ('english_editing_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('scientific_editing', models.CharField(blank=True, choices=[('', '----'), ('Scientific editing', 'Scientific editing')], max_length=20, null=True)),
                ('scientific_editing_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('presubmission_review', models.CharField(blank=True, choices=[('', '----'), ('Presubmission review', 'Presubmission review')], max_length=20, null=True)),
                ('presubmission_review_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('journal_selection', models.CharField(blank=True, choices=[('', '----'), ('Journal selection', 'Journal selection')], max_length=20, null=True)),
                ('journal_selection_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('author_invoice_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_invoice', models.CharField(blank=True, max_length=10, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editingservices.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Target_journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=150)),
                ('publisher_name', models.CharField(max_length=150)),
                ('issn', models.CharField(max_length=150)),
                ('impact_factor', models.CharField(max_length=150)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editingservices.Article')),
            ],
        ),
        migrations.AddField(
            model_name='articlepartner',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editingservices.Partner'),
        ),
        migrations.AddField(
            model_name='articleeditor',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editingservices.Editor'),
        ),
    ]
