# Generated by Django 2.1.1 on 2019-03-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editingservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='expected_delivery_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='paper_received',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='paper_sent_author',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='payment_received_on',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='articleeditor',
            name='editor_payment_sent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='articleeditor',
            name='editor_returned_paper',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='articleeditor',
            name='expected_returned_paper',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='articleeditor',
            name='paper_sent_editor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_invoice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
